/**
 * MATRIZ DE CONTROL DE ACCESO BASADO EN ROLES (RBAC)
 * Sistema de Gestión Inteligente de Salas de Estudio - UTP
 * Define los permisos y visibilidad de módulos para el personal institucional.
 */

// 1. Roles del Sistema
export const ROLES = {
  ADMINISTRADOR: 'ADMINISTRADOR',
  SUPERVISOR: 'SUPERVISOR',
  OPERADOR: 'OPERADOR',
  SEGURIDAD: 'SEGURIDAD',
  RECEPCION_BIBLIOTECA: 'RECEPCION_BIBLIOTECA',
};

// 2. Definición de Permisos
export const PERMISOS = {
  // Módulos
  VER_DASHBOARD: 'VER_DASHBOARD',
  VER_RESERVAS: 'VER_RESERVAS',
  CREAR_RESERVA: 'CREAR_RESERVA',
  LIBERAR_SALA: 'LIBERAR_SALA',
  VER_CAMARAS: 'VER_CAMARAS',
  VER_LISTA_ESPERA: 'VER_LISTA_ESPERA',
  ASIGNAR_LISTA_ESPERA: 'ASIGNAR_LISTA_ESPERA',
  VER_INCIDENCIAS_IA: 'VER_INCIDENCIAS_IA',
  RESOLVER_INCIDENCIA: 'RESOLVER_INCIDENCIA',
  VER_USUARIOS: 'VER_USUARIOS',
  GESTIONAR_USUARIOS: 'GESTIONAR_USUARIOS',
  VER_CONFIGURACION: 'VER_CONFIGURACION',
  EDITAR_CONFIGURACION: 'EDITAR_CONFIGURACION',
  USAR_SIMULADOR: 'USAR_SIMULADOR',
};

// 3. Matriz de Permisos por Rol
export const MATRIZ_PERMISOS = {
  [ROLES.ADMINISTRADOR]: [
    PERMISOS.VER_DASHBOARD,
    PERMISOS.VER_RESERVAS,
    PERMISOS.CREAR_RESERVA,
    PERMISOS.LIBERAR_SALA,
    PERMISOS.VER_CAMARAS,
    PERMISOS.VER_LISTA_ESPERA,
    PERMISOS.ASIGNAR_LISTA_ESPERA,
    PERMISOS.VER_INCIDENCIAS_IA,
    PERMISOS.RESOLVER_INCIDENCIA,
    PERMISOS.VER_USUARIOS,
    PERMISOS.GESTIONAR_USUARIOS,
    PERMISOS.VER_CONFIGURACION,
    PERMISOS.EDITAR_CONFIGURACION,
    PERMISOS.USAR_SIMULADOR,
  ],

  [ROLES.SUPERVISOR]: [
    PERMISOS.VER_DASHBOARD,
    PERMISOS.VER_RESERVAS,
    PERMISOS.CREAR_RESERVA,
    PERMISOS.LIBERAR_SALA,
    PERMISOS.VER_CAMARAS,
    PERMISOS.VER_LISTA_ESPERA,
    PERMISOS.ASIGNAR_LISTA_ESPERA,
    PERMISOS.VER_INCIDENCIAS_IA,
    PERMISOS.RESOLVER_INCIDENCIA,
    PERMISOS.USAR_SIMULADOR,
  ],

  [ROLES.OPERADOR]: [
    PERMISOS.VER_DASHBOARD,
    PERMISOS.VER_RESERVAS,
    PERMISOS.LIBERAR_SALA,
    PERMISOS.VER_CAMARAS,
    PERMISOS.VER_INCIDENCIAS_IA,
    PERMISOS.RESOLVER_INCIDENCIA,
    PERMISOS.USAR_SIMULADOR,
  ],

  [ROLES.SEGURIDAD]: [
    PERMISOS.VER_DASHBOARD,
    PERMISOS.VER_CAMARAS,
    PERMISOS.VER_INCIDENCIAS_IA,
  ],

  [ROLES.RECEPCION_BIBLIOTECA]: [
    PERMISOS.VER_DASHBOARD,
    PERMISOS.VER_RESERVAS,
    PERMISOS.CREAR_RESERVA,
    PERMISOS.VER_LISTA_ESPERA,
    PERMISOS.ASIGNAR_LISTA_ESPERA,
  ],
};

// 4. Mapeo de Pestañas/Módulos a Permisos Requeridos
export const PERMISOS_POR_TAB = {
  dashboard: PERMISOS.VER_DASHBOARD,
  reservas: PERMISOS.VER_RESERVAS,
  camaras: PERMISOS.VER_CAMARAS,
  espera: PERMISOS.VER_LISTA_ESPERA,
  alertas: PERMISOS.VER_INCIDENCIAS_IA,
  usuarios: PERMISOS.VER_USUARIOS,
  configuracion: PERMISOS.VER_CONFIGURACION,
};

// 5. Funciones Helper
export const tienePermiso = (rolUsuario, permiso) => {
  if (!rolUsuario) return false;
  const permisosDelRol = MATRIZ_PERMISOS[rolUsuario] || [];
  return permisosDelRol.includes(permiso);
};

export const puedeAccederTab = (rolUsuario, tabId) => {
  const permisoRequerido = PERMISOS_POR_TAB[tabId];
  if (!permisoRequerido) return true;
  return tienePermiso(rolUsuario, permisoRequerido);
};
